Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # Bot Configuration
# Generated by Telegram Music Bot Maker

import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Bot credentials
BOT_TOKEN = os.getenv("BOT_TOKEN", "8138462822:AAFh8pV4tW2euSuNAnp597-rje3UqFP_Nzg")
API_ID = os.getenv("API_ID", "29887059")
API_HASH = os.getenv("API_HASH", "8173fb6e839cc131ab2341d59763be60")

# Bot settings
BOT_USERNAME = "@BankaiXMusic_bot"
ADMIN_IDS = []  # Add your Telegram user ID here

# Music settings
MAX_SONG_DURATION = 600  # 10 minutes
MAX_QUEUE_SIZE = 50
DOWNLOAD_FOLDER = "downloads"

# Feature flags
FEATURES = {
    "youtube_download": true,
    "spotify_search": true,
    "queue_management": true,
    "volume_control": true,
    "admin_commands": true,
    "auto_delete": true
}

# Messages
WELCOME_MESSAGE = f"""
🎵 Welcome to {BOT_USERNAME}!

I'm your personal music bot ready to serve you the best tunes! 🎶

What I can do:
{'🎧 Download music from YouTube' if FEATURES['youtube_download'] else ''}
{'🔍 Search Spotify tracks' if FEATURES['spotify_search'] else ''}
{'📋 Manage song queue' if FEATURES['queue_management'] else ''}
{'🔊 Volume control' if FEATURES['volume_control'] else ''}
{'👑 Admin commands' if FEATURES['admin_commands'] else ''}

Just send me a song name or use /play <song name>!
"""

ERROR_MESSAGES = {
    "no_results": "❌ No results found for your search.",
    "download_failed": "❌ Failed to download the song. Please try again.",
    "invalid_format": "❌ Invalid format. Please try a different search.",
    "queue_full": "❌ Queue is full! Please wait for some songs to finish.",
    "not_admin": "❌ This command is only available for admins."
}
